### PR TITLE
Allow More Java versions

### PR DESCRIPTION
**Pull request by nemaniarjun**
Fixes a problem at coala org.
Fixes parse_java_version to detect `9-ea` version.

### CODE REVIEW

**Comment by myint** [comment]
It looks like this fails in one of the tests.

https://travis-ci.org/myint/language-check/jobs/190265455

```
Trying:
    parse_java_version('''
    openjdk version "1.8.0_60"
    OpenJDK Runtime Environment (build 1.8.0_60-b27)
    OpenJDK 64-Bit Server VM (build 25.60-b23, mixed mode))
    ''')
Expecting:
    (1, 8)
**********************************************************************
File "download_lt.py", line 45, in download_lt.parse_java_version
Failed example:
    parse_java_version('''
    openjdk version "1.8.0_60"
    OpenJDK Runtime Environment (build 1.8.0_60-b27)
    OpenJDK 64-Bit Server VM (build 25.60-b23, mixed mode))
    ''')
Exception raised:
    Traceback (most recent call last):
      File "/opt/python/pypy3-2.4.0/lib-python/3/doctest.py", line 1288, in __run
        compileflags, 1), test.globs)
      File "<doctest download_lt.parse_java_version[1]>", line 1, in <module>
        parse_java_version('''
      File "download_lt.py", line 56, in parse_java_version
        'Could not parse Java version from """{}""".'.format(version_text))
    SystemExit: Could not parse Java version from """
    openjdk version "1.8.0_60"
    OpenJDK Runtime Environment (build 1.8.0_60-b27)
    OpenJDK 64-Bit Server VM (build 25.60-b23, mixed mode))
    """.
```

**Comment by nemaniarjun** [comment]
Yeah, will update it soon.

**Comment by jayvdb** [comment]
Note this is to resolve https://github.com/myint/language-check/issues/31 .
@nemaniarjun , ping...

**Comment by mrzl** [comment]
@nemaniarjun @myint have you been looking into this?

**Comment by yzgyyang** [comment]
Ping :)

**Comment by nemaniarjun** [comment]
I dont have time to work on this issue right now, If I remember correctly, we just need to set a good regex that works for all versions.

**Pull request closed without merging**
